routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	if ( Auth::check() ) {
		return view('welcome');	
	} else {
		return redirect('login');
	}
});


// Mobile API
Route::get('api/log', 'ApiController@api_log')->name('api_log');
Route::get('qr/{size}/{format}/{key}', 'ApiController@qr')->name('qr');
Route::get('card/{id}', 'ApiController@library_card')->name('card');

Auth::routes();

// admin routes
Route::get('dashboard', 'HomeController@index')->name('home');
Route::get('print', 'HomeController@print_report')->name('print');

// settings
Route::get('settings', 'SettingsController@index')->name('settings');
Route::post('settings/profile', 'SettingsController@profile_update')->name('profile.update');
Route::post('settings/password', 'SettingsController@password_update')->name('password.update');

// Restful Controllers
Route::resources([
	'users' => 'UsersController',
	'roles' => 'RolesController',
	'members' => 'MembersController',
]);

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'first_name', 'last_name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    // https://medium.com/@ezp127/laravel-5-4-native-user-authentication-role-authorization-3dbae4049c8a
    // $request->user()->authorizeRoles(['employee', 'manager']);
    // $request->user()->authorizeRoles('manager');

    public function roles()
    {
      return $this->belongsToMany(Role::class);
    }

    /**
    * @param string|array $roles
    */
    public function authorizeRoles($roles)
    {
      if ( is_array( $roles ) ) {
          return $this->hasAnyRole($roles) || 
                 abort(401, 'This action is unauthorized.');
      }
      
      return $this->hasRole($roles) || 
             abort(401, 'This action is unauthorized.');
    }
    
    /**
    * Check multiple roles
    * @param array $roles
    */
    public function hasAnyRole($roles)
    {
      return null !== $this->roles()->whereIn('name', $roles)->first();
    }

    /**
    * Check one role
    * @param string $role
    */
    public function hasRole($role)
    {
      return null !== $this->roles()->where('name', $role)->first();
    }
}

app/Http/Controllers/UsersController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request; 
use Validator;
use App\User;
use App\Role;
use Auth;

class UsersController extends Controller
{
    /**
     * Instantiate a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');

        $this->params = array(
            'title' => 'Users',
            'description' => 'Manage all users and roles.',
            'roles' => Role::all(),
        );
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $this->params['users'] = User::paginate(10);

        return view('users.index', $this->params);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $this->params['title'] = 'Register new users';
        $this->params['description'] = 'Customize and register new user account.';

        return view('users.create', $this->params);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Block users who are not admin
        $request->user()->authorizeRoles('admin');

        $validate = array(
            'email' => 'required|string|email|max:255|unique:users',
            'name' => 'required|string|max:255',
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'password' => 'required|confirmed|min:6|max:50',
            'password_confirmation' => 'required',
            'user_role' => 'required|array',
        );

        $validator = Validator::make( $request->all(), $validate );

        if ( $validator->fails() ) {
            return redirect('users/create')
                ->withErrors( $validator )
                ->withInput();
        }

        $user = new User();
        $user->fill( $request->all() );
        $user->password = bcrypt( $request->input('password') );
        $user->save();

        // attach user roles.
        foreach ( $request->input('user_role') as $role_id ) {
            $user->roles()->attach( Role::find( $role_id ) );    
        }

        return redirect('users')->with('success', 'User ' . $user->name . ' successfuly added.');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $this->params['title'] = 'Edit User Info';
        $this->params['description'] = 'Update user information.';

        $user = User::find( $id );

        if ( ! $user ) {
            return redirect('users')->with('warning', 'User no longer exist.');
        }

        $roles = array();
        foreach ( $user->roles()->get() as $role ) {
            $roles[] = $role->id;
        }

        $this->params['user'] = $user;
        $this->params['user_roles'] = $roles;

        return view('users.edit', $this->params);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update( Request $request, $id )
    {

        // Block users who are not admin
        $request->user()->authorizeRoles('admin');

        $validate = array(
            'name' => 'required|string|max:255',
            'first_name' => 'required|string|max:255',
            'last_name' => 'required|string|max:255',
            'user_role' => 'required|array',
        );

        $user = User::find( $id );

        // double check if user exist.
        if ( ! $user ) {
            return redirect('users')->with('error', 'User does not exist, please try again.');
        }

        // check user email if changed.
        if ( $user->email != $request->input('email') ) {
            $validate['email'] = 'required|string|email|max:255|unique:users';
        }

        $validator = Validator::make( $request->all(), $validate );

        if ( $validator->fails() ) {
            return redirect('users/'. $user->id .'/edit')
                ->withErrors( $validator )
                ->withInput();
        }

        $user->fill( $request->all() );
        $user->save();

        // Remove all user roles
        $user->roles()->detach();        

        // attach user roles.
        foreach ( $request->input('user_role') as $role_id ) {
            $user->roles()->attach( Role::find( $role_id ) );    
        }

        return redirect('users/'. $user->id .'/edit')->with('success', 'User details successfuly updated.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy( Request $request, $id )
    {
        // Block users who are not admin
        $request->user()->authorizeRoles('admin');

        $user = User::find( $id );

        if ( ! $user ) {
            return response()->json([
                'error' => true,
                'message' => 'Please try again.'
            ]);
        } 

        $user->roles()->detach();
        $user->delete();

        return response()->json([
            'error' => false,
            'message' => 'User successfuly removed.'
        ]);
    }
}
 

resources/views/users/create.blade.php
@extends('admin')



@section('content')

<div class="panel panel-default panel-shadow" data-collapsed="0" style="direction: ltr;">
	
	<div class="panel-heading">
		<div class="panel-title">Add User</div>
		
		<div class="panel-options"></div>
	</div>
	
	<!-- panel body -->
	<div class="panel-body">
		
		<form action="{{ route('users.store') }}" method="POST" role="form">
			{{ csrf_field() }}

			<div class="row">
				<div class="col-md-6">

					<div class="form-group">
						<label for="email">Email</label>
						<input type="email" value="{{ old('email') }}" name="email" class="form-control" id="email" placeholder="email">
					</div>

					<div class="form-group">
						<label for="username">Username</label>
						<input type="text" value="{{ old('name') }}" name="name" class="form-control" id="username" placeholder="username">
					</div>

					<div class="form-group">
						<label for="first_name">First Name</label>
						<input type="text" value="{{ old('first_name') }}" name="first_name" class="form-control" id="first_name" placeholder="first name">
					</div>

					<div class="form-group">
						<label for="last_name">Last Name</label>
						<input type="text" value="{{ old('last_name') }}" name="last_name" class="form-control" id="last_name" placeholder="last name">
					</div>

				</div>
				<div class="col-md-6">

					<div class="form-group">
						<label for="new_password">Password</label>
						<input type="password" name="password" class="form-control" id="new_password" placeholder="Password">
					</div>

					<div class="form-group">
						<label for="password_confirmation">Repeat Password</label>
						<input type="password" name="password_confirmation" class="form-control" id="password_confirmation" placeholder="Repeat Password">
					</div>

					<label for="user_role">User Role</label>

					@if( $roles )
					@foreach( $roles as $role )
					
					@if( $role->name == 'admin' )
						<div class="form-group">
							<div class="checkbox i-checks">
								<label> <input type="checkbox" name="user_role[]" value="{{ $role->id }}"><i></i> {{ ucfirst( $role->name ) }} </label>
							</div>
						</div>
					@endif
					
					@endforeach
					@endif
					
					<button type="submit" class="btn btn-primary">Save User <i class="fa fa-save"></i></button>
				</div>
			</div>
		
		</form>
		
	</div>
</div>

@endsection

@section('action')
<div class="title-action">
<a href="{{ route('users.index') }}" class="btn btn-white">
	Back <i class="fa fa-chevron-left"></i> 
</a>
</div>
@endsection


@section('styles')
<link href="{{asset('css/plugins/iCheck/custom.css')}}" rel="stylesheet">
@endsection

@section('scripts')
<!-- iCheck -->
<script src="{{asset('js/plugins/iCheck/icheck.min.js')}}"></script>
    <script>
        $(document).ready(function () {
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
        });
    </script>
@endsection

resources/views/users/edit.blade.php
@extends('admin')


@section('content')


<div class="panel panel-default panel-shadow" data-collapsed="0" style="direction: ltr;">
	
	<div class="panel-heading">
		<div class="panel-title">User Information</div>
		
		<div class="panel-options"></div>
	</div>
	
	<!-- panel body -->
	<div class="panel-body">
		
		<form action="{{ route( 'users.update', $user->id ) }}" method="POST" role="form">
			{{ csrf_field() }}
			<input type="hidden" name="_method" value="PUT">
			<div class="row">
				<div class="col-md-6">

					<div class="form-group">
						<label for="email">Email</label>
						<input type="email" value="{{ $user->email }}" name="email" class="form-control" id="email" placeholder="email">
					</div>

					<div class="form-group">
						<label for="username">Username</label>
						<input type="text" value="{{ $user->name }}" name="name" class="form-control" id="username" placeholder="username">
					</div>

					<div class="form-group">
						<label for="first_name">First Name</label>
						<input type="text" value="{{ $user->first_name }}" name="first_name" class="form-control" id="first_name" placeholder="first name">
					</div>

					<div class="form-group">
						<label for="last_name">Last Name</label>
						<input type="text" value="{{ $user->last_name }}" name="last_name" class="form-control" id="last_name" placeholder="last name">
					</div>

					<button type="submit" class="btn btn-primary">
						<i class="fa fa-save"></i> Save
					</button>

				</div>
				<div class="col-md-6">

					<div class="form-group">
						<label for="last_name">Reset Password</label>
						<p><i>Users can request for a password reset upon clicking on <strong>forgot password</strong> in the login page. Password reset link will be sent to the user's email account.</i></p>
					</div>

					<label for="user_role">User Role</label>
					
					@if( $roles )
					@foreach( $roles as $role )

					<div class="form-group">
						<div class="checkbox i-checks">
							<label> <input type="checkbox" {{ in_array($role->id, $user_roles) ? 'checked':'' }} name="user_role[]" value="{{ $role->id }}"><i></i> {{ ucfirst( $role->name ) }} </label>
						</div>
					</div>
					
					@endforeach
					@endif
					
				</div>
			</div>
		
		</form>

	</div>
</div>


@endsection

@section('action')
<div class="title-action">
<a href="{{ route('users.index') }}" class="btn btn-white">
	Back <i class="fa fa-chevron-left"></i> 
</a>
</div>
@endsection

@section('styles')
<link href="{{asset('css/plugins/iCheck/custom.css')}}" rel="stylesheet">
@endsection

@section('scripts')
<!-- iCheck -->
<script src="{{asset('js/plugins/iCheck/icheck.min.js')}}"></script>
    <script>
        $(document).ready(function () {
            $('.i-checks').iCheck({
                checkboxClass: 'icheckbox_square-green',
                radioClass: 'iradio_square-green',
            });
        });
    </script>
@endsection

resources/views/users/index.blade.php
@extends('admin')

@section('content')


<div class="panel panel-default panel-shadow" data-collapsed="0" style="direction: ltr;">
	
	<div class="panel-heading">
		<div class="panel-title">User List<small class="m-l-sm"> Manage all user accounts.</small></div>
		
		<div class="panel-options"></div>
	</div>
	
	<!-- panel body -->
	<div class="panel-body">
		@if( $users )
			
		<div class="table-responsive">
			<table class="table table-bordered table-striped table-hover">
				<thead>
					<tr>
						<th>Username</th>
						<th>Email</th>
						<th>Roles</th>
						<th>Options</th>
					</tr>
				</thead>
				<tbody>
					@foreach( $users as $user )

						<tr id="user-row-{{ $user->id }}">
							<td>{{ $user->name }}</td>
							<td>{{ $user->email }}</td>
							<td>
								@if( $user->roles()->get() )
								@foreach( $user->roles()->get() as $role )
								<span class="badge badge-info">{{ $role->name }}</span>
								@endforeach
								@endif
							</td>
							<td>
								<a href="{{ url("users/{$user->id}/edit") }}" class="btn btn-success btn-xs">
									<i class="fa fa-edit"></i> Edit
								</a>
								@if( Auth::user()->id != $user->id ) 
								<button data-id="{{ $user->id }}" data-name="delete" class="btn btn-danger btn-xs" data-toggle="modal" data-target="#remove-user">
									<i class="fa fa-close"></i> Remove
								</button>
								@endif
							</td>
						</tr>

					@endforeach
				</tbody>
			</table>
		</div>
		
		{{ $users->links() }}
		@endif
	</div>
</div>

<div class="modal inmodal" id="remove-user" tabindex="-1" role="dialog"  aria-hidden="true">
    <div class="modal-dialog modal-sm">
        <div class="modal-content animated fadeIn">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                <h4 class="modal-title">Remove User</h4>
            </div>
            <div class="modal-body">
                <p><strong>Are you sure?</strong> once removed, this user will no longer be able to login on his/her account and all data affiliated to this account will be deleted.</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="pull-left btn btn-white"  data-dismiss="modal">Cancel</button>
                <button type="button" id="remove-btn" class="btn btn-danger">Remove</button>
            </div>
        </div>
    </div>
</div>

@endsection

@section('action')
<div class="title-action">
    <a href="{{ route('users.create') }}" class="btn btn-primary">Add User <i class="fa fa-plus"></i></a>
</div>
@endsection

@section('styles')
<!-- Toastr style -->
<link href="{{asset('css/plugins/toastr/toastr.min.css')}}" rel="stylesheet">
@endsection

@section('scripts')
<!-- Toastr script -->
<script src="{{asset('js/plugins/toastr/toastr.min.js')}}"></script>
<script>
jQuery(document).ready(function() {

	toastr.options = {
		"closeButton": true,
		"debug": false,
		"progressBar": true,
		"positionClass": "toast-top-right",
		"onclick": null,
		"showDuration": "400",
		"hideDuration": "1000",
		"timeOut": "7000",
		"extendedTimeOut": "1000",
		"showEasing": "swing",
		"hideEasing": "linear",
		"showMethod": "fadeIn",
		"hideMethod": "fadeOut"
	}

	jQuery('button[data-name="delete"]').click(function(e) {
		e.preventDefault();
		var token = jQuery('meta[name="csrf-token"]').attr('content');
	});

	jQuery('#remove-user').on('show.bs.modal', function (event) {
		var button = jQuery(event.relatedTarget); // Button that triggered the modal
		var user_id = button.data('id');
		jQuery('#remove-btn').data('id',user_id);
  		jQuery(this).find('.modal-title').text('Remove ' + jQuery('#user-row-'+user_id+' td:first').html() );
	});

	jQuery('#remove-btn').click(function(e) {
		e.preventDefault();
		var user_id = jQuery(this).data('id');
		var token = jQuery('meta[name="csrf-token"]').attr('content');

		jQuery.ajax({  
			url: '{{ route('users.index') }}/'+user_id,
			type: 'POST',
			dataType: 'json',
			data: { _token: token, _method: 'DELETE' },
		})
		.always(function(data) {
			if (data.error) {
				toastr.error(data.message,'Error');
			} else {
				jQuery('#remove-user').modal('toggle');
				toastr.success(data.message,'Success');
				jQuery('#user-row-'+user_id).remove();
			}
		});
		 
	});

});
</script>
@endsection